Repository FelipeGaleao/fast-api-kafka, pull requests merged in 2023-06, with the labels that each got.

#8 [FIX] Ajuste nas configurações do Docker
  consumer/dockerfile
  consumer/main.py
  docker-compose.yml
  producer/app/main.py
  producer/dockerfile
  producer/requirements.txt
Labels: enhancement

#13 [FEATURE] Adicionando endpoint enviar_horario_ponto
  producer/app/main.py
Labels: enhancement

#15 [DOCS] Criada documentação de commits semânticos
  docs/commits_semantico.md
  docs/commits_semanticos.md
Labels: documentation, medium

#17 feat: ajuste no metodo de comprovante de matricula
  producer/app/main.py
Labels: enhancement

#30 docs: adicionada documentacao 'Getting Started' guia
  docs/guia_inicial.md
Labels: documentation, medium

#18 docs: corrigida documentacao sobre commits semanticos
  docs/commits_semantico.md
Labels: documentation, medium

#32 feat: Adicionado informação sobre classe matrícula aos docs
  docs/informacao_classe_matricula.md
Labels: enhancement

#33 [FEATURE] Alterações no registro de ponto
  producer/app/main.py
Labels: bug, enhancement
